Add new FAQ about metapackage and include install snippets to intro
Qiskit/documentation pull request #2516
Opened 2024-12-20 17:46 UTC by kaelynj

Closes #2486 and #2488

2024-12-20 21:13 UTC, abbycross commented on docs/faq.mdx
> +## What happened to Qiskit Aer, Qiskit Nature, Qiskit Experiments, etc.?
```suggestion
## What happened to Python distributions such as Qiskit Aer, Qiskit Nature, and Qiskit Experiments?
```

2024-12-20 21:14 UTC, abbycross commented on docs/faq.mdx
> +Before the release of the Qiskit SDK v1.0, Qiskit was comprised of many different Python distributions such as: `qiskit-terra`, the compiler core; `qiskit-aer`, the high-performance simulator; the or
```suggestion
Before the release of the Qiskit SDK v1.0, Qiskit was comprised of many different Python distributions, such as `qiskit-terra`, the compiler core; `qiskit-aer`, the high-performance simulator; the original IBM Quantum™ provider; and several now-obsolete packages providing particular exploratory algorithmic or experiment-running features. 
```

2024-12-20 21:15 UTC, abbycross commented on docs/faq.mdx
> +These separate software packages were combined together into what was called the Qiskit *metapackage* which allowed users to install all of these components together through `pip install qiskit`. Thi
```suggestion
These separate software packages were combined into what was called the Qiskit *metapackage*, which allowed users to install all of these components together through `pip install qiskit`. This metapackage architecture was removed with the release of the Qiskit SDK v1.0, and now each of the individual software distributions need to be installed separately. 
```

2024-12-20 21:16 UTC, abbycross commented on docs/faq.mdx
> +Check out the [Qiskit ecosystem](https://www.ibm.com/quantum/ecosystem) to find the package you may be looking for. You can also read the [1.0 migration guide](./migration-guides/qiskit-1.0-installat
```suggestion
Visit the [Qiskit ecosystem](https://www.ibm.com/quantum/ecosystem) to find the package to suit your needs. You can also read the [v1.0 migration guide](/migration-guides/qiskit-1.0-installation#why-these-changes-happened) for more information about this change.
```

2025-01-06 22:12 UTC, abbycross commented on docs/faq.mdx
> +These separate software packages were combined into what was called the Qiskit *metapackage*, which allowed users to install all of these components together through `pip install qiskit`. This metapa
```suggestion
These separate software packages were combined into what was called the Qiskit *metapackage*, which allowed users to install all of these components together through `pip install qiskit`. This metapackage architecture was removed with the release of the Qiskit SDK v1.0, and now each of the individual software distributions needs to be installed separately. 
```

2025-01-06 22:13 UTC, abbycross commented on docs/faq.mdx
> +These separate software packages were combined into what was called the Qiskit *metapackage*, which allowed users to install all of these components together through `pip install qiskit`. This metapa
whoops, I missed this first time around!

2025-01-06 22:30 UTC, Eric-Arellano commented on docs/guides/index.mdx
> +If you'd like to start using Qiskit Serverless right, install it with pip:
@abbycross I tihnk this is wrong. More generally, I'm not sure if the install snippets throughout the file follow the right style?

2025-01-13 15:58 UTC, abbycross commented on docs/guides/index.mdx
> +If you'd like to start using Qiskit Serverless right, install it with pip:
```suggestion
To start using Qiskit Serverless right away, install it with pip:
```

2025-01-13 15:58 UTC, abbycross commented on docs/guides/index.mdx
> +If you'd like to start using Qiskit Serverless right, install it with pip:
Is this what you meant @Eric-Arellano?

2025-01-13 16:04 UTC, Eric-Arellano commented on docs/guides/index.mdx
> +If you'd like to start using Qiskit Serverless right, install it with pip:
Yes, Abby, that is what I meant. I'm also not sure we need to say "right away"?

I also meant to say that we should probably use consistent wording with the prefix sentence for all the install snippets, such as `The catalog can be installed via pip:`

2025-01-13 19:00 UTC, abbycross commented on docs/guides/index.mdx
> +If you'd like to start using Qiskit Serverless right, install it with pip:
Here's what IBM Style says:

> Use this term, which means by way of, to refer to routing data, such as in “Messages are routed via SMTP”. In
other situations, try to replace via with one of the following synonyms: across, along, by, from, on, or through.

"Routing data" seems very specific - do we consider installing a package the same as data being routed to your machine?

2025-01-13 19:17 UTC, Eric-Arellano commented on docs/guides/index.mdx
> +If you'd like to start using Qiskit Serverless right, install it with pip:
Sort of? I think Becky normally uses "with pip"? That should translate better.

2025-01-13 21:04 UTC, javabster requested changes

2025-01-13 21:04 UTC, javabster commented on docs/faq.mdx
> +## What happened to Python distributions such as Qiskit Aer, Qiskit Nature, and Qiskit Experiments?
I think we should be more explicit here and warn people that since March 2024 (or whatever date we released the metapackage change) the command `pip install qiskit` will only install the Qiskit SDK (and link to the github repo), not the other packages.

2025-01-13 21:04 UTC, javabster commented on docs/guides/index.mdx
>  ## Qiskit Transpiler as a Service
shouldn't we also include some pip install commands for the transpiler service and addons?

2025-01-14 16:00 UTC, kaelynj commented on docs/guides/index.mdx
>  ## Qiskit Transpiler as a Service
Just added install commands for them

2025-01-14 16:29 UTC, kaelynj commented on docs/faq.mdx
> +## What happened to Python distributions such as Qiskit Aer, Qiskit Nature, and Qiskit Experiments?
I added another couple sentences at the beginning of this section. Let me know if it seems sufficient!

2025-01-16 18:12 UTC, javabster reviewed
A few minor changes after that LGTM

2025-01-16 18:12 UTC, javabster commented on docs/faq.mdx
> +Since the release of the Qiskit SDK v1.0, the command `pip install qiskit` will **only** install the [Qiskit SDK](https://github.com/Qiskit/qiskit). This means that some modules that you have used in
```suggestion
Since the release of the Qiskit SDK v1.0, the command `pip install qiskit` will **only** install the [Qiskit SDK](https://github.com/Qiskit/qiskit). This means that some modules that you have used in the past, such as `qiskit-aer` or `qiskit-nature`, now have to be installed separately.
```

technically they cant install terra separately bc it doesnt exist anymore

2025-01-16 18:12 UTC, javabster commented on docs/faq.mdx
> +Visit the [Qiskit ecosystem](https://www.ibm.com/quantum/ecosystem) to find the package to suit your needs. You can also read the [v1.0 migration guide](/migration-guides/qiskit-1.0-installation#why-
```suggestion
If you want to install the packages that used to be included in the Qiskit metapackage you can visit the [Qiskit ecosystem](https://www.ibm.com/quantum/ecosystem) to find a range of packages to suit your needs. You can also read the [v1.0 migration guide](/migration-guides/qiskit-1.0-installation#why-these-changes-happened) for more information about this change.
```

The ecosystem sentence sounded a bit disjointed so added a bit more context

2025-01-17 19:42 UTC, javabster approved these changes
LGTM 🚀

2025-01-17 19:47 UTC, merged